### ISSUE TITLE
Consider building ARM64 releases and containers

### ISSUE THREAD

**Issue by spkane** [BigJk/end_of_eden#3]
Just stumbled upon this today. I am enjoying taking a look at what you have done.

Since everything appears to build perfectly on an arm64 (Apple silicon) Mac, it would be really nice to have pre-built binaries in the GH releases, for both Linux and Darwin arm64 (via setting `GOOS` and `GOARCH`). 

And from my initial tests something like the following should also build and push the image for both Linux architectures as well.

`docker buildx build --file ./Dockerfile --platform linux/amd64,linux/arm64 --tag ghcr.io/bigjk/end_of_eden:master --push .`

Keep up the good work!

**Comment by spkane** [comment]
I needed to update the `Dockerfile` with a patch like the one below to prevent it from complaining during runtime about the **GLIBC** version. I assume this is because the `builder` image and the `deploy` image have different versions of **GLIBC** installed.

Happy to PR some of this if you would like.

```diff
diff --git a/Dockerfile b/Dockerfile
  index 22f721a..0c624e1 100644
  --- a/Dockerfile
  +++ b/Dockerfile
  @@ -8,8 +8,8 @@ COPY . .
   RUN apt-get update
   RUN apt-get install -y libasound2-dev

  -RUN go build -tags no_audio -o /app/end_of_eden ./cmd/game
  -RUN go build -tags no_audio -o /app/fuzzy_tester ./cmd/internal/fuzzy_tester
  +RUN CGO_ENABLED=0 go build -tags no_audio -o /app/end_of_eden ./cmd/game
  +RUN CGO_ENABLED=0 go build -tags no_audio -o /app/fuzzy_tester ./cmd/internal/fuzzy_tester

   # Disable SSH for now
   # RUN go build -tags no_audio -o /app/end_of_eden_ssh ./cmd/game_ssh
```

**Comment by BigJk** [comment]
Thanks for the input! I added arm64 docker builds and apple silicon binary releases 😃

**Comment by spkane** [comment]
Awesome. Glad to hear it. Thanks!
